#-------------------------------
# General Site Settings
baseURL = "https://k11.netlify.app/"
title = "recuc.com"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 12
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "en"
    contentDir = "content/en"
    weight = 1

  [languages.vi]
    languageName = "vi"
    contentDir = "content/vi"
    weight = 2

  [[params.hero.vi]]
    hero__title = "Khám phá biên giới kỹ thuật số"
    hero__description = "Dẫn dắt bởi kinh nghiệm, chúng tôi khám phá thế giới động của công nghệ web, cung cấp những đánh giá toàn diện và kiến thức sâu sắc."
    
#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    identifier = 'home'
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Domains"
    identifier = 'domains'
    url = "/domains/"
    weight = 2

  [[menu.main]]
    name = "Hosting"
    identifier = 'hosting'
    url = "/hosting/"
    weight = 3

  [[menu.main]]
    name = "Servers"
    identifier = 'servers'
    url = "/servers/"
    weight = 4

  [[menu.main]]
    name = "AI"
    identifier = 'ai'
    url = "/ai/"
    weight = 5
	
  [[menu.main]]
    name = "Reviews"
    identifier = 'reviews'
    url = "/reviews/"
    weight = 6

  [[menu.main]]
    name = "Tags"
    identifier = 'tags'
    url = "/tags/"
    weight = 7
	
  [[menu.main]]
    name = "Pages"
    identifier = 'pages'
    weight = 8
    hasChildren = true

  [[menu.main]]
    parent = "pages"
    name = "About"
    identifier = 'about'
    url = "/about/"
    weight = 1

  [[menu.main]]
    parent = "pages"
    name = "Elements"
    identifier = 'elements'
    url = "/elements/"
    weight = 2

  [[menu.main]]
    parent = "pages"
    name = "Contact"
    identifier = 'contact'
    url = "/contact/"
    weight = 3

  [[menu.main]]
    parent = "pages"
    name = "Videos"
    identifier = 'videos'
    url = "/videos/"
    weight = 4

  [[menu.main]]
    parent = "pages"
    name = "Featured"
    identifier = 'featured'
    url = "/featured/"
    weight = 5

  [[menu.main]]
    parent = "pages"
    name = "Latest"
    identifier = 'latest'
    url = "/posts/"
    weight = 6
	
  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Get in touch"


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo.png"
  description = "recuc.com is a news and magazine Hugo theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Exploring the Digital Frontier"
    hero__description = "Guided by experience, we delve into the dynamic world of web tech, providing comprehensive reviews and insightful knowledge."

  #-------------------------------
  # Tags Section Settings
  [params.tags_section]
    enable = true
    number_posts = 6 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
    number_columns = 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.

  [[params.tag]]
    tag = "domains"

  [[params.tag]]
    tag = "hosting"

  [[params.tag]]
    tag = "servers"

  [[params.tag]]
    tag = "ai"
	
  [[params.tag]]
    tag = "reviews"

  # You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = true
    section_title = "Meet our authors"


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # recuc.com comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "recuc.com" # Add your shortname for Disqus Comment. For example recuc.com


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
